"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-15 08:25:18.760160

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sort_name", sa.Text(), nullable=False),
        sa.Column("mbid", sa.Text(), nullable=True),
        sa.Column("discogs_id", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_artists_mbid", "artists", ["mbid"], unique=False)
    op.create_index("idx_artists_name", "artists", ["name"], unique=False)
    op.create_index("idx_artists_sort_name", "artists", ["sort_name"], unique=False)
    op.create_table(
        "libraries",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("incoming_path", sa.Text(), nullable=False),
        sa.Column("staging_path", sa.Text(), nullable=False),
        sa.Column("library_path", sa.Text(), nullable=False),
        sa.Column("archive_path", sa.Text(), nullable=False),
        sa.Column("watch_enabled", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "auto_approve_threshold", sa.Float(), server_default=sa.text("(0.90)"), nullable=False
        ),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operations",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("operation_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("is_dry_run", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("affected_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.Text(), nullable=True),
        sa.Column("snapshot_id", sa.LargeBinary(length=16), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["rollback_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rollback_snapshots",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("operation_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("snapshot_data", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("restored_at", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "albums",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("sort_title", sa.Text(), nullable=False),
        sa.Column("album_artist_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("mbid", sa.Text(), nullable=True),
        sa.Column("release_group_mbid", sa.Text(), nullable=True),
        sa.Column("discogs_id", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("genre", sa.Text(), nullable=True),
        sa.Column("disc_count", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("track_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_compilation", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_albums_artist", "albums", ["album_artist_id"], unique=False)
    op.create_index("idx_albums_mbid", "albums", ["mbid"], unique=False)
    op.create_index("idx_albums_title", "albums", ["title"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("library_id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("job_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("(100)"), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("parent_job_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_jobs_claim", "jobs", ["status", "job_type", "priority", "created_at"], unique=False
    )
    op.create_index("idx_jobs_library", "jobs", ["library_id", "status"], unique=False)
    op.create_index("idx_jobs_parent", "jobs", ["parent_job_id"], unique=False)
    op.create_table(
        "media_server_state",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("library_id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("plugin_id", sa.Text(), nullable=False),
        sa.Column("server_url", sa.Text(), nullable=True),
        sa.Column("db_path", sa.Text(), nullable=True),
        sa.Column("config", sa.Text(), nullable=True),
        sa.Column("last_sync_at", sa.Text(), nullable=True),
        sa.Column("last_sync_status", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_media_server_state_library", "media_server_state", ["library_id"], unique=False
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("library_id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("(100)"), nullable=False),
        sa.Column("conditions", sa.Text(), nullable=False),
        sa.Column("actions", sa.Text(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("library_id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("album_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("artist_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("zone", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_modified", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("track_number", sa.Integer(), nullable=True),
        sa.Column("disc_number", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("bit_depth", sa.Integer(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("codec", sa.Text(), nullable=True),
        sa.Column("is_lossless", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("mb_recording_id", sa.Text(), nullable=True),
        sa.Column("composer", sa.Text(), nullable=True),
        sa.Column("genre", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("has_embedded_art", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_corrupt", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("overall_confidence", sa.Float(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_path"),
    )
    op.create_index("idx_tracks_album", "tracks", ["album_id"], unique=False)
    op.create_index("idx_tracks_file_path", "tracks", ["file_path"], unique=True)
    op.create_index("idx_tracks_library_zone", "tracks", ["library_id", "zone"], unique=False)
    op.create_index("idx_tracks_mb_recording", "tracks", ["mb_recording_id"], unique=False)
    op.create_index(
        "idx_tracks_needs_review",
        "tracks",
        ["needs_review"],
        unique=False,
        sqlite_where=sa.text("needs_review = TRUE"),
    )
    op.create_index("idx_tracks_quality", "tracks", ["quality_score"], unique=False)
    op.create_table(
        "change_history",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("operation_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("track_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("change_type", sa.Text(), nullable=False),
        sa.Column("field_name", sa.Text(), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column("old_file_path", sa.Text(), nullable=True),
        sa.Column("new_file_path", sa.Text(), nullable=True),
        sa.Column("old_zone", sa.Text(), nullable=True),
        sa.Column("new_zone", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "duplicate_groups",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("library_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("match_type", sa.Text(), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("best_track_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("track_count", sa.Integer(), nullable=False),
        sa.Column("detected_at", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'open'"), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["best_track_id"],
            ["tracks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_identity",
        sa.Column("track_id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("content_hash_sha256", sa.Text(), nullable=False),
        sa.Column("fingerprint_data", sa.LargeBinary(), nullable=True),
        sa.Column("fingerprint_duration", sa.Float(), nullable=True),
        sa.Column("fingerprint_hash", sa.Text(), nullable=True),
        sa.Column("acoustid_id", sa.Text(), nullable=True),
        sa.Column("acoustid_score", sa.Float(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_modified", sa.Text(), nullable=False),
        sa.Column("hash_computed_at", sa.Text(), nullable=True),
        sa.Column("fingerprint_computed_at", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("track_id"),
    )
    op.create_index("idx_file_identity_acoustid", "file_identity", ["acoustid_id"], unique=False)
    op.create_table(
        "metadata_confidence",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("track_id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("field_name", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_metadata_conf_track", "metadata_confidence", ["track_id"], unique=False)
    op.create_index(
        "idx_metadata_confidence_track_field",
        "metadata_confidence",
        ["track_id", "field_name"],
        unique=True,
    )
    op.create_table(
        "duplicate_members",
        sa.Column("group_id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("track_id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("quality_score", sa.Integer(), nullable=False),
        sa.Column("is_best", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("zone", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["duplicate_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "track_id"),
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("library_id", sa.LargeBinary(length=16), nullable=False),
        sa.Column("track_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("album_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("duplicate_group_id", sa.LargeBinary(length=16), nullable=True),
        sa.Column("review_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("resolved_at", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_group_id"],
            ["duplicate_groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_review_library_status", "review_items", ["library_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_review_library_status", table_name="review_items")
    op.drop_table("review_items")
    op.drop_table("duplicate_members")
    op.drop_index("idx_metadata_confidence_track_field", table_name="metadata_confidence")
    op.drop_index("idx_metadata_conf_track", table_name="metadata_confidence")
    op.drop_table("metadata_confidence")
    op.drop_index("idx_file_identity_acoustid", table_name="file_identity")
    op.drop_table("file_identity")
    op.drop_table("duplicate_groups")
    op.drop_table("change_history")
    op.drop_index("idx_tracks_quality", table_name="tracks")
    op.drop_index(
        "idx_tracks_needs_review", table_name="tracks", sqlite_where=sa.text("needs_review = TRUE")
    )
    op.drop_index("idx_tracks_mb_recording", table_name="tracks")
    op.drop_index("idx_tracks_library_zone", table_name="tracks")
    op.drop_index("idx_tracks_file_path", table_name="tracks")
    op.drop_index("idx_tracks_album", table_name="tracks")
    op.drop_table("tracks")
    op.drop_table("rules")
    op.drop_index("idx_media_server_state_library", table_name="media_server_state")
    op.drop_table("media_server_state")
    op.drop_index("idx_jobs_parent", table_name="jobs")
    op.drop_index("idx_jobs_library", table_name="jobs")
    op.drop_index("idx_jobs_claim", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("idx_albums_title", table_name="albums")
    op.drop_index("idx_albums_mbid", table_name="albums")
    op.drop_index("idx_albums_artist", table_name="albums")
    op.drop_table("albums")
    op.drop_table("rollback_snapshots")
    op.drop_table("operations")
    op.drop_table("libraries")
    op.drop_index("idx_artists_sort_name", table_name="artists")
    op.drop_index("idx_artists_name", table_name="artists")
    op.drop_index("idx_artists_mbid", table_name="artists")
    op.drop_table("artists")
    # ### end Alembic commands ###
